export const products = [
  {
    id: 1,
    title: "Siemens BQD360 3 Pole 480V 60 Amp Circuit Breaker",
    description: "Interruptor de 3 polos 480V 60 Amp",
    details: "Interruptor termomagnético Siemens BQD360 de 3 polos, 480 voltios, 60 amperios. Protección industrial de alta capacidad.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/q320.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/q320.jpg"],
    price: 165.99,
    category: "interruptores-3p",
  },
  {
    id: 2,
    title: "Siemens BQD340 3 Pole 480V 40 Amp Circuit Breaker",
    description: "Interruptor de 3 polos 480V 40 Amp",
    details: "Interruptor termomagnético Siemens BQD340 de 3 polos, 480 voltios, 40 amperios. Protección industrial robusta.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/q320.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/q320.jpg"],
    price: 165.99,
    category: "interruptores-3p",
  },
  {
    id: 3,
    title: "Siemens BQD330 3 Pole 480V 30 Amp Circuit Breaker",
    description: "Interruptor de 3 polos 480V 30 Amp",
    details: "Interruptor termomagnético Siemens BQD330 de 3 polos, 480 voltios, 30 amperios. Ideal para aplicaciones comerciales.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/q320.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/q320.jpg"],
    price: 165.99,
    category: "interruptores-3p",
  },
  {
    id: 4,
    title: "Siemens BQD320 3 Pole 480V 20 Amp Circuit Breaker",
    description: "Interruptor de 3 polos 480V 20 Amp",
    details: "Interruptor termomagnético Siemens BQD320 de 3 polos, 480 voltios, 20 amperios. Protección confiable para cargas medianas.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/q320.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/q320.jpg"],
    price: 165.99,
    category: "interruptores-3p",
  },
  {
    id: 5,
    title: "Siemens BQD315 3 Pole 480V 15 Amp Circuit Breaker",
    description: "Interruptor de 3 polos 480V 15 Amp",
    details: "Interruptor termomagnético Siemens BQD315 de 3 polos, 480 voltios, 15 amperios. Protección residencial y comercial ligera.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/q320.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/q320.jpg"],
    price: 165.99,
    category: "interruptores-3p",
  },
  {
    id: 6,
    title: "Siemens Q2100 2 Pole 120/240V 100 Amp Circuit Breaker",
    description: "Interruptor de 2 polos 120/240V 100 Amp",
    details: "Interruptor termomagnético Siemens Q2100 de 2 polos, 120/240 voltios, 100 amperios. Alta capacidad para cargas pesadas.",
    image: "/IMGPRODUCTS/Interruptores_2_polos/Q2100-1.jpg",
    images: ["/IMGPRODUCTS/Interruptores_2_polos/Q2100-1.jpg"],
    price: 37.99,
    category: "interruptores-2p",
  },
  {
    id: 7,
    title: "Siemens BQD3100 3 Pole 480v 100 Amp Circuit Main Breaker",
    description: "Interruptor principal de 3 polos 480V 100 Amp",
    details: "Interruptor principal termomagnético Siemens BQD3100 de 3 polos, 480 voltios, 100 amperios. Protección principal para sistemas industriales.",
    image: "/IMGPRODUCTS/Interruptores_3_polos/q320.jpg",
    images: ["/IMGPRODUCTS/Interruptores_3_polos/q320.jpg"],
    price: 189.99,
    category: "interruptores-3p",
  },
];
